#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"

# Create a regex for a conventional commit.
convetional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   echo "${GREEN} ✔ Commit message meets Conventional Commit standards\e[0m"
   exit 0
fi

echo "${RED}❌ Commit message does not meet the Conventional Commit standard!"
echo "An example of a valid message is: "
echo "  feat(login): add the 'remember me' button"
echo "ℹ More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
exit 1